### ISSUE TITLE
Meeting times?

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#1]
Amber and Connor -- what would be a good time for a weekly meeting?

I'm on campus MWF. The best time for me would be after class, but I could also do lunchtime or, if necessary, before 10 AM. If we sometimes need to reschedule, it's OK with me if it's not at the exact same time every single week.
@amberpeddicord @ChinoyIndustries

**Comment by ChinoyIndustries** [comment]
I'm free after class MWF till 6.

**Comment by ebeshero** [comment]
@haggis78 I edited your post just now to use the `@username` to "ping" your GitHub partners on this repo. That means the issue will go directly to their notifications--more likely they'll see it quickly. :-)

**Comment by amberpeddicord** [comment]
@haggis78 I'm free MWF between 11 and 3 and after class Friday or possibly Wednesday if we need to meet then!
