### ISSUE TITLE
Collating J

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#10]
@ChinoyIndustries  -- I'm putting this up so it can be added to the "projects" to-do chart on Github. In case you weren't around the day we looked at this in class, if you go to the Github BreconChurch website, you'll see a tab for "projects". This allows us to move things around on a workflow chart. Issues can be dropped in to make a to-do list. I'm adding this one so we can keep track of your collation of witness J.

We worked out the syntax for divergent readings, as well as for page breaks. I can show you that after class on Friday -- I'm assuming that you're busy figuring out Image Magick between now and then. -WHC

**Comment by ChinoyIndustries** [comment]
Finished.

One question: are we distinguishing between ampersands and 'et'? There is only a single place in the collation in which the distinction between the two is already marked with an <app>, however, there are a number of places where J uses the opposite of whichever one is given in the collation. Shall I go and mark those, or remove the one existing instance that is marked?
