### ISSUE TITLE
Project Special Meeting: M 11/4 @ 4pm after class

### ISSUE THREAD

**Issue by ebeshero** [haggis78/BreconChurch#12]
@haggis78 @amberpeddicord @ChinoyIndustries @alnopa9 @KSD32 We're calling a special meeting of Brecon Team on Monday to review the XPath-ability of your markup and do some experiments with the code that will help with your next stage of project development.  We need **ALL** members of the team to be present also to assess what markup tasks remain. 

Some very important projects tasks have yet to be completed, and the team requires some material from @ChinoyIndustries. This includes: 

* Image processing for the website (via ImageMagick)
* collation of witnesses J and C with TEI critical apparatus markup. 

We are aware that @ChinoyIndustries may need a review of coding decisions made in his absence these past few weeks. Therefore it is even more important that @ChinoyIndustries be present for this meeting!

We want to complete all the XML markup for this project in the next 2 weeks because we are beginning new tasks involved with XSLT transformation and processing/analyzing the collation data, and we expect **all** team members to be involved.

**Comment by ebeshero** [comment]
@ChinoyIndustries Some of the team is waiting for you to add collation markup to the XML files before they can proceed. The team needs to know whether you are going to be committing anything so that it can make progress.

**Comment by ChinoyIndustries** [comment]
@ebeshero Apologies for my absence. I do not mean to be a deadbeat project partner, so to speak. J is now collated.

@haggis78 Do we have yet the image specifications needed to present the images on the website? If so I can process those at once.
