### ISSUE TITLE
Witness D

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#17]
@ChinoyIndustries -- I just had a look at D. It's a bit busier than our other MSS. There are notes in the margin, but as far as I can tell, they are just guide words summarizing what is in the text next to it. These we can ignore. However, there are also numerous insertions and corrections within the text itself, written between the lines. We haven't figured out how we are coding that with the TEI yet (though TEI includes provisions for all of that), nor have we figured out how it will be presented in the final webpage. But please do make a thorough note of all of those things, which will be really important for figuring out the relationship among the manuscripts. Thanks!

**Comment by haggis78** [comment]
I am now collating #D.

**Comment by ChinoyIndustries** [comment]
Working on D too as well as generally cleaning up the document.

**Comment by haggis78** [comment]
@ChinoyIndustries at this point, for consistency, it would be best not to have two people working on the same witness. D is more complicated than the others. Can you prepare the images of R instead?

**Comment by haggis78** [comment]
Pulling xml to try to finish up #D!

**Comment by haggis78** [comment]
Pushed xml. Done for tonight. xml has everything done except for checking some things in R and the printed witnesses. I will check R after you have those images ready, since that will make it easier and more efficient. Can you check the queries in the printed witnesses after the images are ready?
