### ISSUE TITLE
Some preliminary findings!

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#18]
I ran an XPath search over the xml file as we have it so far:

    ```//rdg[contains(@wit, "O") and contains(@wit, "C")]```

And so on with each pair of witnesses, to see how frequently they agree. There are 242 apps in which each pair can agree or disagree.

Unsurprising finding: Using R as a base, W (earliest printing) is closer than S (second printing), which in turn is closer than J (third printing). Each printing was based on the prior one, so more errors crept in with each printing.

Interesting finding: O agrees with I 197 times (the closest match among the three c. 1700 MSS we've done so far, CDIO, still waiting on D). O also agrees with C 187 times. But I and C agree only 174 times. Thus I and C both agree with O more often than they agree with one another. That supplies a hypothesis that I and C were both copied from O, though again where D fits in we don't know yet.

Surprising finding: Of all of the witnesses so far, the closest one to R is... drumroll please... W! W agrees with R 119 times, while the second-closest, I, only agrees with R 79 times. This means that although W is a few generations removed from the lost original Letters Patent (someone made a transcript for Willis, he copied it from there, he sent it to the printer, the printer typeset it), W is *still* considerably more accurate than O, I, or C. Fascinating.

Somewhat surprising but perhaps explicable: The MS copies, CIO, are all closer to W than they are to R. Could they have copied from Willis? Maybe, but probably not -- R might be more of an outlier due to sixteenth-century spellings that CIO and W all changed to c. 1700 spellings. But it's worth a deeper look. 

All of this is preliminary, of course. We will see how D changes the picture, and I've got some cleaning up to do in the xml file. Even after finding all the final numbers, it only supplies hypotheses that need to be checked with specific readings. But this is the sort of data that all the coding makes possible.

**Comment by ebeshero** [comment]
@haggis78 This is exciting to see, and I'm glad you're able to scope these preliminary findings with XPath! (You may want just to try plotting these out in SVG as witness pairings... What's a good way to display this?)

**Comment by ebeshero** [comment]
@haggis78 I begin to think this may be well represented in a set of bar plots representing percentages of agreement. Out of all the variant apps, how frequently do distinct pairings of editions agree?
