### ISSUE TITLE
Resolving collation

### ISSUE THREAD

**Issue by ChinoyIndustries** [haggis78/BreconChurch#22]
As we finish up the collation with #D, here's a thread for us to make decisions on individual words and <app>'s that are still in question.

**Comment by haggis78** [comment]
Good idea. I intend to execute a pull around 7 PM and work on collating more of #D this evening. I'll let you know once I've pushed it back up.

**Comment by haggis78** [comment]
OK, done for tonight. Pushed the xml. I figured out the correct way to mark up superscripts, reviewed your work from D, and pushed a bit further ahead.

**Comment by haggis78** [comment]
Pulling #D.

**Comment by haggis78** [comment]
Done with #D for the day. Pushed xml back up.
