### ISSUE TITLE
Project ODD HTML documentation and source TEI on Brecon site?

### ISSUE THREAD

**Issue by ebeshero** [haggis78/BreconChurch#26]
@haggis78 @amberpeddicord @ChinoyIndustries Would you like to feature the HTML documentation of your TEI ODD on the website? Perhaps you could highlight (link directly to) particular portions of it to indicate any customizations of TEI elements that are potentially interesting, or just share it by way of documenting your encoding decisions. Also finding a place to make the source TEI XML available (perhaps by link to your GitHub repo, or perhaps simply as download from the site itself) is a good practice for serious TEI encoding projects, for a community of scholars in which "Share your source code" is kind of a mantra.

**Comment by ebeshero** [comment]
What I'd suggest is to make a space on your site to explain your project methodology with some attention to your encoding methods, to be shared with a mixed community that includes people like you (coding students and historians alike) with some interest (even introductory) in manuscript paleography and digital methods. A really fine example of such documentation is the "Methodology" page from the Emily Dickinson Project: http://dickinson.newtfire.org/methodology.html

**Comment by amberpeddicord** [comment]
@ebeshero I can get started on this now!

**Comment by haggis78** [comment]
@amberpeddicord Is there some part of the methodology that I can be working on in parallel? If you've already started I don't know what you might be doing as to structure, and I don't want to work at cross-purposes.

**Comment by ebeshero** [comment]
Just a comment from the sidelines here: I think it'll be good for @amberpeddicord to organize this documentation, and perhaps @haggis78 you can supplement as needed.

**Comment by haggis78** [comment]
Sounds good.

**Comment by ebeshero** [comment]
Of course I really didn't do that on my first DH project, in which I was in your position, @haggis78. I wrote up the documentation myself, but I think it might be better this way. :-)
