### ISSUE TITLE
README.md Updates?

### ISSUE THREAD

**Issue by amberpeddicord** [haggis78/BreconChurch#27]
@haggis78 @ChinoyIndustries Hey team! 

I was looking at our project repo, and I noticed that it's been some time since we looked at our README.md file. I think it would help if one of us added more information about our project to it, since it's the first thing people will see when they come to our repo. Right now, we only have a few of our sources listed there, so I think adding more about our project and our team's goals would help!

**Comment by haggis78** [comment]
@amberpeddicord @ChinoyIndustries I'm on it. I'll write something up and you can edit it if you want.
