### ISSUE TITLE
Font style issues on CSS

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#28]
@ebeshero @amberpeddicord @ChinoyIndustries @alnopa9 We'd noticed that the strikethroughs and superscripts we marked up in the xml weren't presenting as such in the html. I added a few lines to the CSS that I hope will accomplish that, If not, they will be easy to find -- they are all the way at the bottom of the CSS.

Now, how to present in html a situation where one scribe actually overwrote another scribe's text? H'mmm. That may need to be rendered as a strikethrough and superscript too.

**Comment by amberpeddicord** [comment]
@haggis78 I updated the server, so those changes should be visible on the site now!

**Comment by haggis78** [comment]
@amberpeddicord Didn't work -- trying a different syntax.

**Comment by haggis78** [comment]
@amberpeddicord Somehow I created another merge conflict? Working on it. Grrr.

**Comment by haggis78** [comment]
@amberpeddicord Solved. I think it was actually because I pushed README.md and then didn't pull before pushing the CSS. Anyway, the new CSS should now be up. Let's give that a try.

**Comment by amberpeddicord** [comment]
@haggis78 Updated the server again! Let me know if that worked.

**Comment by haggis78** [comment]
@amberpeddicord Alas no.

**Comment by haggis78** [comment]
@amberpeddicord I'm OK with our not solving this particular problem today.

**Comment by alnopa9** [comment]
@haggis78 I added your superscripts to witness D. To make text a superscript in HTML you just wrap it in `<sup>` tags.
[commit](https://github.com/haggis78/BreconChurch/commit/79db261726ce4673f3e71bacf4f289ff01bd894b)
