### ISSUE TITLE
Menubar and page scrolling issue

### ISSUE THREAD

**Issue by amberpeddicord** [haggis78/BreconChurch#30]
I'm not sure if this is just an issue on my end, but our menubar javascript is having some issues on the site. On most of the pages, once the bar gets to the top of the page, it jumps back down and won't let me scroll to the bottom of the page. 

@alnopa9 @haggis78 @ChinoyIndustries @ebeshero

**Comment by haggis78** [comment]
@amberpeddicord Yes, that's happening on mine too. It was happening to me before (like earlier this week) but only on the home page index.html. Now it's happening on others. A possibility: I pushed updates to all the SSI's this morning, but the only thing I touched was the Manuscripts drop-down, which I renamed Witnesses. I did start with the Index page and copy and paste from there, so if there's any problem somehow embedded in that bit of the SSI, that could explain how it propagated across the site. But what it could actually be, I can't imagine. BTW I'm currently editing other stuff, specifically the xml and the msDesc xslt.

**Comment by haggis78** [comment]
@amberpeddicord Have you pushed anything this AM?

**Comment by amberpeddicord** [comment]
@haggis78 Yes, I've pushed some html for the methodology page up!

**Comment by haggis78** [comment]
@amberpeddicord OK. I've got a merge conflict, but I think it's actually an unresolved one from last night -- a merge file was created and somehow I need to find and delete it.

**Comment by haggis78** [comment]
@amberpeddicord So if you could avoid touching the xml, msDesc.xslt, and the output text.html while I try to resolve this, we can avoid creating a more serious conflict. Gah.

**Comment by haggis78** [comment]
@amberpeddicord OK, looks resolved now. Carry on.

**Comment by ebeshero** [comment]
@haggis78 Sorry about the merge issues! If you are updating all the SSI’s, you should probably re-rerun the comparison.xslt that I revised late last night. I removed the special comparison-page-ssi file reference from the comparison.html output last night so we could view the editions locally and check the state of witness D (now appearing with all its variants to the end). 

If you re-run that XSLT, you’ll just restore the SSI line on comparison.html.

**Comment by ebeshero** [comment]
@haggis78 See the last posts on: https://github.com/haggis78/BreconChurch/issues/29

**Comment by haggis78** [comment]
@ebeshero OK, reran, saved the html, and pushed it.

**Comment by haggis78** [comment]
@amberpeddicord @ebeshero I've discovered another problem with the menu bar. From certain pages -- I think all of them except home -- if I mouse over either "Witnesses" or "Comparison", both menus drop down at the same time, one on top of the other. That means that the top of one menu is inaccessible behind the other menu. Also, the pages with the individual transcriptions no longer work in the "Witnesses" drop-down, except from the home page. I might be at fault for that since I copied the same new code across all of the SSIs, though I don't know why it would work in one and not in others. (There was a native difference before in the urls that were linked: index-ssi had longer hrefs such as: `<a href="html/transcripts/display/display-R.html">Manuscript R</a>` while I think the others had a shorter form, something like  '<a href="/display-R.html">Manuscript R</a>` (from my memory). But why would this matter?

**Comment by alnopa9** [comment]
@haggis78 @amberpeddicord @ebeshero I'm looking into the problem now.

**Comment by ebeshero** [comment]
@haggis78 @alnopa9 Yes--I was noticing that too, but it didn't actually register with me that there was something *behind* the short menu on the top. I also noticed that the links on each of the Witnesses on that menu don't go anywhere. I'm wondering whether you need that Witnesses section of the menu at all now that the Comparison view serves as a viewer for the individual witnesses?

**Comment by ebeshero** [comment]
The overlap-of-menu-sections is particularly problematic here: http://brecon.newtfire.org/html/edition-svg.html

**Comment by ebeshero** [comment]
Just a reminder of @amberpeddicord's initial post: We're having trouble scrolling down on most pages on the site. Something stops me as I'm scrolling and bounces to the top of the page.

**Comment by haggis78** [comment]
I agree with @ebeshero -- the individual witness views are probably not actually necessary since we have the comparison viewer. I do plan to make a page with a more precise transcription of R (original spellings etc.) interspersed with the MS images, but not today.

**Comment by alnopa9** [comment]
@haggis78 @amberpeddicord @ebeshero Sorry, I actually ended up going grocery shopping. Now, I'm looking into the problem. I'm noticing the jumping as well, but only on certain pages and it happens once you reach the actual top of the nav bar on scroll. 

Other problems I'm noticing:
- broken links
- css problems on the Anonymous Blocks page
- overlapping on drop down menus

I'll try and debug this, but first I'm going to look at previous commits and see what code was changed.

**Comment by ebeshero** [comment]
Thanks @alnopa9 ! I was wondering if you might want direct access to the web server to make the debugging easier...but you and @amberpeddicord may want to sort that out.

**Comment by haggis78** [comment]
@amberpeddicord @amberpeddicord I've also realized that there is no link in the menu for TextualAnalysis.html. It's in the repo but not connected to the site. It should be listed in the Analysis drop-down menu. I don't want to go messing with that while you're still debugging the menu bar, though.

**Comment by alnopa9** [comment]
@haggis78 I'll add that in while I'm working on it.

**Comment by alnopa9** [comment]
@ebeshero @ebeshero @haggis78 I solved the problem and it makes me want to face palm myself... Somehow with all the changes and merge conflicts, we lost the closing `</div>` for the ssi. That's all. I just had to add the closing tag. 🙃

**Comment by haggis78** [comment]
@alnopa9 You know, I'd noticed that the opening `<div>` tag was flagged, but I thought "heck, it seems to be working, so that must not matter". Never occurred to me that _that might be why it was not in fact working._

**Comment by haggis78** [comment]
@alnopa9 @amberpeddicord I re-did stemma.html and just pushed it. Can that be inserted at the bottom of textualanalysis.html? Amber, I think I understood you to say in the past week that you'd figured out how to do this?

**Comment by amberpeddicord** [comment]
@haggis78 Yes! If you look at the code for the timeline.html it shows how I did it, but basically you just have to put the code for the svg (including the ```<svg>``` tags) into a div in the html.

**Comment by haggis78** [comment]
@amberpeddicord Heck, sounds simple enough that even I can probably do it. Thanks.

**Comment by amberpeddicord** [comment]
@haggis78 @alnopa9 I updated the server and all looks well! Except there are now *two* menu bars on the main page, but I'm assuming this is an easy fix.

**Comment by alnopa9** [comment]
@haggis78 @amberpeddicord Yeah, don't push anything yet.

**Comment by alnopa9** [comment]
@amberpeddicord @haggis78 It's easy to fix, but I have to go to work. I get off at 10.
Amber, you could probably fix it. Basically, when I was viewing it locally, I forgot to take out the navbar code from the page. So, that is rendering and the SSI is also inserting its own nav bar. Just remove my code between the two comments where the ssi line goes. (That's why I have thatset up that way because I'm forgetful).
Dr. Campbell, no. You can push to the repo freely. I just have some littlethings I fixed on my end, but I can push them later.

**Comment by haggis78** [comment]
@alnopa9 Thank you for your hard work! So should we leave off pushing anything to github until we get an all-clear from you?

**Comment by haggis78** [comment]
@amberpeddicord Success pasting the stemma.svg code into the xslt to output the TextualAnalysis.html. Thanks.
