### ISSUE TITLE
Avoiding merge conflicts

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#32]
@amberpeddicord -- since we're waiting to hear from Alyssa tonight before pushing anything, let's keep track together of anything we've worked on since our last push so we can avoid merge conflicts once we do. Henceforth I'm going to be pushing files one by one.

I've changed stemma.svg, stemma.html, TextualAnalysis.xsl, TextualAnalysis.html, and history.html. I think that's it. 

 I'm going to go grade papers and will come back to all of this around 10 PM so I can push files once Alyssa's back and gives us the all clear.

**Comment by alnopa9** [comment]
@haggis78 Sorry, I edited my comment to say that you guys can push to the repo freely.

**Comment by alnopa9** [comment]
@haggis78 so, push whatever you've done changes to! :+1:

**Comment by haggis78** [comment]
@amberpeddicord @alnopa9 OK, I have pushed every file I touched, did a pull too to make sure, and everything up and down the tree is clean. I have to go out (one does not simply miss choir rehearsal this close to Christmas) but will check back in around 9:30.
