### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#33]
@amberpeddicord @alnopa9 @ebeshero Here are the bugs that I'm aware of:

- [x] Drop-down menu giving access to individual witnesses only works from home page
- [x] Page showing witness D by itself does not include the variants (red text). Similar to the former problem with the last part of D on the Comparison page. The D page must not have been output from the XML and display.xsl since I actually collated D. Not having output this in the first place, I'm not sure how one outputs a single-witness page.
- [x] On the Comparison page, witnesses W, S, and J do not show up at all when their boxes are ticked. Odd- they worked before. -Possibly related: In the main XML file, I put more detail into the `<bibl>` elements for these three witnesses, which could complicate the XSLT transforming what was once the straightforward `<bibl>` text (there are now numerous elements within `<bibl>` such as `<author>` etc.). That may create complications for W S and J when they show up on the single-witness pages, since they currently just have that older, simpler text string. But that text does not show up anyway on the Comparison page. It's just the one change I can think of that the three all have in common.
- [x] The drop-down menu is horizontally compressed on the Analysis - ab page, covering some things up, I think.
- [x] texts.html works on the site but wasn't associated with the CSS. I just did that and pushed it, but since the SSI/navbar/etc is still up in the air, I didn't add that. 
Anyone got anything else?

**Comment by ebeshero** [comment]
@haggis78 @amberpeddicord @alnopa9  Uh oh. It looks like something went wrong with a website update. It's getting late now, so I think the wisest course of action, given the complexity of these bugs, is to give Team Brecon an extension until tomorrow night on this. Is that likely to be helpful?

**Comment by ebeshero** [comment]
I'm seeing double on the home page...a double title bar and nav bar.

**Comment by amberpeddicord** [comment]
@ebeshero @haggis78 @alnopa9 I think an extension might be helpful for sure. I know that earlier Alyssa said she had a few small changes that still need pushed, so that might fix some of the bugs.

**Comment by haggis78** [comment]
@amberpeddicord @alnopa9 @ebeshero That would be great as far as I'm concerned.

**Comment by ebeshero** [comment]
Consider an extension granted. I think these bugs are pretty complex, actually, because your site is so intricate at this point. It's a design challenge! (And a learning opportunity, so it's totally worth it.) And of course you want to finish this last coding sprint with a beautiful and functional site!

**Comment by alnopa9** [comment]
@ebeshero @amberpeddicord @haggis78 Sorry, I just finished dinner and getting Parker ready for bed. Diving in to the code now! 🏊‍♀

**Comment by alnopa9** [comment]
@ebeshero @amberpeddicord So, I just wanted to see if I actually have permissions on the server, that way I wouldn't keep bothering Amber. Turns out, I don't. As long as Amber is okay with it, would I be able to gain permission to the server to make the site functional faster?

**Comment by amberpeddicord** [comment]
@ebeshero @alnopa9 I'm perfectly fine with that! Is there something I need to do to give you permission?

**Comment by alnopa9** [comment]
@ebeshero I'm not entirely sure how she would go about this. Is it just her changing the file permissions?

**Comment by ebeshero** [comment]
@alnopa9 I thought you had permission as a member of the Brecon group! (I thought I'd set all the instructor team as members of each student group this term.)  Let me check on the web server...But if you do, you might not be able to write over files that Amber is the owner of. That's okay: what you do is delete the old file and upload your new file in its place.

**Comment by ebeshero** [comment]
@alnopa9 I've verified that you (as ama277) are indeed a member of the brecon team group, so you do have access to the directory on newtfire. Let me check and make sure your webspace lets members of the group have write access...

**Comment by ebeshero** [comment]
@alnopa9 Uh oh...wait a sec. The group doesn't have write access...I'm changing that now.

**Comment by ebeshero** [comment]
@alnopa9 Okay--brecon team has write access to the directory. The way the web server seems to work is that it recognizes whoever posts as the owner of a given file, and if another team member tries to update the same file, it stops them. You'll probably still not be allowed to save overtop of files that @amberpeddicord has posted, so the way to deal with that is to delete the file and upload a new copy.

**Comment by alnopa9** [comment]
@ebeshero I'm updating what I've fixed to the server now!

**Comment by alnopa9** [comment]
@hagis @amberpeddicord @ebeshero I think I fixed all of the bugs that you've found so far. I'm going to do one final push to the repo for the night.
[commit](https://github.com/haggis78/BreconChurch/commit/41b0913850b446eedafb445bbb98797953eb0210)

I just went through all of the links to double check and make sure that was broken. I think they are all working, but if anyone wants to take 5 minutes tomorrow and triple check, that'd be great.

**Comment by haggis78** [comment]
@alnopa That's fantastic. Thank you so much!

**Comment by haggis78** [comment]
@alnopa9 @amberpeddicord Now we have a zombie bug: the red text has disappeared from the last third of the Comparison D text again!

**Comment by haggis78** [comment]
@amberpeddicord You and @alnopa9 worked really hard on the "Comparison: Anonymous Blocks" page, and it looks great, but I don't think that users will have any idea what it tells us. Can you write up a paragraph to add at the top so people know what they're looking at? Also I'm unsure whether there's a bug in the AB 1 box: it looks as if some data are missing (compare with the word-count and string-count for it).

**Comment by alnopa9** [comment]
@haggis78 I reran the comparison xslt and updated the server. Witness D is up to date again. I'll rerun the xslts for the Comparison AB page and see if that helps.

**Comment by alnopa9** [comment]
@haggis78 I'm looking at the Comparison AB page in both Firefox and Chrome and in Firefox, the chart is appears in tact. I think there may be a bug in chrome that is stopping parts of the column svg from fully rendering. @ebeshero Have you seen this happen before?

**Comment by alnopa9** [comment]
@haggis78 I'm looking at the Comparison AB page in both Firefox and Chrome and in Firefox, the chart is appears in tact. I think there may be a bug in chrome that is stopping parts of the column svg from fully rendering. @ebeshero Have you seen this happen before?

**Comment by alnopa9** [comment]
@haggis78 @ebeshero I checked through Microsoft Edge and the chart appears whole on it as well.

**Comment by haggis78** [comment]
@alnopa9 @ebeshero Huh. I cleared my cache in Chrome and it still looks like this:
![image](https://user-images.githubusercontent.com/39171157/70819242-b6aeb880-1da3-11ea-849c-5553d1a22457.png)

**Comment by ebeshero** [comment]
@alnopa9 @haggis78 I'm a little confused here, so I'm just going to post a screen shot from my Firefox browser. Firefox and Chrome show me exactly the same issue when I select to compare word count and string length SVG's: I think this is a different problem than what you're seeing, Bill, but I'll post mine just so we can see it:

<img width="1440" alt="Screenshot 2019-12-13 12 24 06" src="https://user-images.githubusercontent.com/4014518/70819343-02616200-1da4-11ea-99f5-69d44186e1ae.png">

**Comment by ebeshero** [comment]
The problem that I see is that when we try to view the SVG plots side by side, the string-counts graph gets cut off. That's something we can manage with a combination of CSS and the `@viewBox` dimensions in the SVG, I think.  Also we could revisit *if* and *when* you need such a long scale on those Word Count plots.

**Comment by ebeshero** [comment]
Let me see if I can duplicate the problem you're seeing, @haggis78 .

**Comment by ebeshero** [comment]
@haggis78 @alnopa9 Yes indeed, I see the same problem that @haggis78 identifies in Chrome with part of AB #1's table not carrying data. I'm looking at the code to see if I can isolate what's not working there and why.

**Comment by ebeshero** [comment]
@alnopa9 I'm going to try to access it via the Developer tools in Chrome... want to try the same? You might spot what's happening before I will...

**Comment by haggis78** [comment]
@alnopa9 @ebeshero It's also missing Witness R in the last two blocks. 
![image](https://user-images.githubusercontent.com/39171157/70820609-135fa280-1da7-11ea-844a-aacc2a847cf0.png)

**Comment by ebeshero** [comment]
@alnopa9 Can you help us understand the architecture of this page? From what I'm seeing in the element inspectors, I think you're outputting the text that goes in the little SVG table for an AB, and at the same moment generating the lines for the two possible SVG graphs that appear to its right. 

The CSS then controls what we're allowed to see at the same time, right? So if I want to compare string-counts and word-counts, the tables go to `display:none` or something like that.

 I think there must be some confusion on specific elements about what's allowed to display at specific moments, and that there's something that's making this ambiguous/unclear for Chrome. My suspicion is that we may want to look at the JavaScript. But we could also do something different in the XSLT to make things easier. I still don't know exactly what it is, but I think we need to be clear about *how* the page is working to do its display first of all.

**Comment by alnopa9** [comment]
@haggis78 @ebeshero I think I found a cause for the bug. I'm changing something in the XSLT now.

**Comment by ebeshero** [comment]
By the way, this is a classic "rabbit-hole" and I want to step back to say, Priority 1 right now is writing good documentation to explain to a visitor *how* to navigate this page and what kinds of information to find here. 

A second priority might be to get your `<title>` element tool-tips to display on the SVG lines, which make the interactivity of the page even better when they work! Mine aren't working right now (sigh).

**Comment by ebeshero** [comment]
@alnopa9 Can you help to document the page architecture for future generations of coders?

**Comment by alnopa9** [comment]
@ebeshero On it now.

**Comment by ebeshero** [comment]
Documentation of *how to read this page*, on the other hand, is probably something the team members who did the collation work can be writing up... You could mock it up in a new GitHub issue and then port it to the comparison page on the website?

**Comment by alnopa9** [comment]
@ebeshero I'm rewriting the XSLT for the chart now to make it's output easier to read when looking at the code. I'm not sure what I was on when I wrote this because the code is **all over the place**. 😞 I'm including more `<g>` with classes that help identify what you are looking at when viewing the code.

**Comment by ebeshero** [comment]
@alnopa9 There's one kind of code that we write in haste to "get stuff to work right now," and another kind of code we write to make it so we can even access our work and understand it and share it with others. Not many programmers are patient enough to take care to write that second kind of code, but there are some that make human-readable, self-documenting code a philosophy of their work. It's really a kind of writing to do that--and we don't sometimes think of code as writing, but it really is. :-) And it's hard to do but it always helps! :-)

**Comment by amberpeddicord** [comment]
Sorry all, I just got home from work! @haggis78 What do you need me to work on next?

**Comment by haggis78** [comment]
@amberpeddicord While @alnopa9 is debugging the code, could you write a paragraph to go at the top of this page (Comparison - Anonymous Blocks) explaining what it represents?

**Comment by alnopa9** [comment]
@haggis78 @amberpeddicord I wrote one for it, but I'm sure Amber could better articulate the purpose for it.

**Comment by alnopa9** [comment]
@ebeshero I think I made it more readable.
[commit](https://github.com/haggis78/BreconChurch/commit/c3982c39dd10b70ea1aa107ea57d87969a3c2c49)
[edition-svg](https://raw.githubusercontent.com/haggis78/BreconChurch/master/site/img/svg/edition-svg.svg)

**Comment by alnopa9** [comment]
@ebeshero @haggis78 Now, I'll rewrite the actual edition.html.

Edit: Actually, I think I'll rewrite the string and word count svg to be output together. With the word count bar graph on top of the string count.

**Comment by ebeshero** [comment]
@alnopa9 Are you noticing as I am how the word count tables don't line up with their graphs when we switch them on to view? That's probably worth changing b/c it makes it hard to read across the page and line up a particular AB. It might mean some spacing issues for viewing the word count tables by themselves...

**Comment by alnopa9** [comment]
@ebeshero Sorry, I was working all weekend and didn't get a chance to do anything on the site. I have noticed that and I think I've come up with a solution for it.
