### ISSUE TITLE
Patent Roll images

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#35]
@ChinoyIndustries I just had an idea (wish I'd had it earlier!): can you put together a quick html page TODAY, entitled "Patent Roll Images and Transcription", and push it to the repo so it can be added to the site? I don't have the proper transcription ready, but you could just put the `<ab>` images in sequence, and then I'll be able to add the text later? Please let us know ASAP if you're going to be able to do that.

@amberpeddicord If @ChinoyIndustries is able to do so, could you add a line to the "Witnesses' drop-down menu, just below "Source Descriptions" and above "Manuscript R"?

**Comment by alnopa9** [comment]
@haggis78 I already made an html page like that.
[commit](https://github.com/haggis78/BreconChurch/blob/master/site/html/patent-collection.html)
What do you want the tab to be called for the nav bar?

**Comment by alnopa9** [comment]
@haggis78 I added the patent-collection.html to the site and it now has a spot on all of the nav bars.
[commit](https://github.com/haggis78/BreconChurch/commit/0eb92c4a25ed362bf906bd01771a169e6087e6ab)

**Comment by haggis78** [comment]
@alnopa9 Perfect -- thanks!
