### ISSUE TITLE
Comparison menu

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#39]
@alnopa9 @amberpeddicord I'm not sure why, but the drop-down menu for Comparison isn't working, and hasn't been for a few weeks. Can this be fixed? It's a key feature of the site (arguably the single most important feature). I'd like to include reference to this in some things in the near future (including a grant application), so if that could be restored to operability as a priority, I would greatly appreciate it. Thank you!

**Comment by alnopa9** [comment]
@haggis78 I just took it down because I was working on the viewer, but I can have it back up this afternoon when I get home from work.

**Comment by alnopa9** [comment]
@haggis78 I just updated the pages to include the comparison pages again.
@amberpeddicord Can you update the server?

**Comment by alnopa9** [comment]
@haggis78 @amberpeddicord and I put the comparison pages back up.
