### ISSUE TITLE
Beginning the collation

### ISSUE THREAD

**Issue by amberpeddicord** [haggis78/BreconChurch#4]
I started looking into the xml document that @haggis78 posted and I'm a little confused on what documents we should be comparing! Should we follow the URL sources in the comment at the top? Or are there other files somewhere else?

**Comment by ChinoyIndustries** [comment]
Yeah, the different versions of the text we're collating into the XML are found at those URL sources in the comment. They're two versions of this document that are online already, for us to compare to the new version being provided by @haggis78. Awaiting your call on what markup style we should use for distinguishing revisions!

**Comment by haggis78** [comment]
Connor is correct. At some point we may wish to download images of these pages to use in constructing our website, especially if the permissions come through for us to post manuscript images. And you can feel free to download them now if that's helpful to you.

**Comment by ebeshero** [comment]
@haggis78 @ChinoyIndustries @amberpeddicord A suggestion to make these sources a little easier to find and navigate: Can one of you prepare a markdown file (like the Readme.md in your repo) to list out the sources with linked URLs? You (well, we) could also mock up a bit of sample code to show what you have in mind for the critical apparatus perhaps on the same document. Markdown files can be pushed and pulled from a repo and are often helpful in planning stages like this! Any of you can get this started—the filename can be anything that makes sense, as in `codePrep.md` or even just the `Readme.md` on your repo. The filename “Readme” is kind of a convention among people who share code to provide documentation that “ports with” the work you are doing, useful to the project team and outsiders alike.
