### ISSUE TITLE
Batchwork for Image Magick

### ISSUE THREAD

**Issue by ebeshero** [haggis78/BreconChurch#5]
@ChinoyIndustries and @ebeshero will meet to experiment with Image Magick to do batch image size reduction at command line (shell). We are permitted to work with images in Box that are inside `Welsh Fasti 2018 > Brecon_Files_for_Box > R_C66_709_Patent_Roll`.

**Comment by ebeshero** [comment]
@ChinoyIndustries Before we meet, make sure you have Image Magick installed: https://imagemagick.org/ 
And here's I think the main resource we want to look at--the command line scripts!
https://imagemagick.org/script/command-line-processing.php

**Comment by ebeshero** [comment]
@ChinoyIndustries Here's some documentation we found for preserving file names in a batch conversion: https://www.imagemagick.org/discourse-server/viewtopic.php?t=32899 (This is iterating over the files in a for-loop.)

**Comment by ChinoyIndustries** [comment]
Success!
