### ISSUE TITLE
ODD Customization

### ISSUE THREAD

**Issue by amberpeddicord** [haggis78/BreconChurch#7]
@ebeshero I went through and deleted modules that we wouldn't need for the project, and I'm at the point of downloading the ODD! I downloaded it as an ODD Customization and a RelaxNG Compact.

What are the next steps that I should take?

(Also, I created a new label called "project progress" so that we could document issues that are about these sort of "next steps" issues. @haggis78 @ChinoyIndustries let me know if I should make edits to this or other labels!)

**Comment by ebeshero** [comment]
@amberpeddicord Terrific! I see that you have saved the ODD file in a dedicated directory in the repo--and that's where it should stay through the project. What we'll do next is customize the schema to allow us an `<empty/>` element the way we discussed last week. And we'll write in some custom attribute values to identify the reading witnesses. Then we'll prepare a new Relax NG schema from that. 

I'm used to writing this part in oXygen, but I want to take a look at the Roma JS tool to see how well it handles these customizations. My colleague has warned me that the Roma JS tool might be a little glitchy for modifying elements, but I'll take a look. If you, @haggis78 , and @ChinoyIndustries  have a few minutes after class tomorrow, I'd like to go over the ODD and its  schema with you and show you how to work with it.

**Comment by ebeshero** [comment]
@haggis78 Can you remind us of the identifiers you want to use for each edition you're comparing? We can work those into the ODD customization!

**Comment by ebeshero** [comment]
Also, after reviewing [some TEI GitHub issues](https://github.com/TEIC/TEI/issues/1801) and [contributions on the TEI listserv](https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1808&L=TEI-L&D=0&P=12380), I think I was in the wrong to suggest the use of the `<empty/>` element inside an empty `<rdg>`, or rather, if we do that, we're probably committing tag abuse. `<empty/>` has a specific purpose in TEI ODD files, and that is to indicate an element like `<milestone/>` that is supposed to be self-closing. 

What we were discussing was that it was important to include information about witnesses where they simply contain nothing, where the other witnesses have text at a given spot. For that, the discussions are telling me what's preferred is simply:
```xml
<ab>The quick brown fox jumped over the
   <app>
       <rdg wit="A">lazy</rdg>
       <rdg wit="B"/>
       <rdg wit="C">sleeping</rdg>
   dog.</ab>
```
Here, witness B simply reads, "The quick brown fox jumped over the dog" while the other two have special adjectives for the dog. 

What we were worried about was perhaps failing to indicating the witness by forgetting to fill it out. I think the less, um, abusive approach to the TEI in this might be to use the `@cause` attribute that comes with the text critical elements. Maybe this is a good way?

```xml
<ab>The quick brown fox jumped over the
   <app>
       <rdg wit="A">lazy</rdg>
       <rdg wit="B" cause="empty"/>
       <rdg wit="C">sleeping</rdg>
   dog.</ab>
```

The attribute can give us a specific way to categorize HOW the witness varies. And perhaps you can think of other values to include here if the variation has something to do with, say, something ornamental or abbreviated?  @haggis78 @ChinoyIndustries @amberpeddicord

**Comment by ebeshero** [comment]
Also, let's take a look at this bundle of attributes and suggested values: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.textCritical.html 
@haggis78 Do any of these look useful?

**Comment by haggis78** [comment]
@ebeshero The identifiers for the printed editions are:

>W: Browne Willis, _An History of the Mitred Parliamentary Abbies, and Conventual Cathedral Churches, Shewing the Times of Their Respective Foundations, and what Alterations They Have Undergone..._ vol. II (1719: this is the transcription we're using as the base text)
>S: John Stevens, _The History of the antient abbeys, monasteries, hospitals, cathedral and collegiate churches. Being two additional volumes to Sir William Dugdale..._ (London, 1722-23), vol. II, Appendix doc. 464 (https://archive.org/details/b30454529_0003/page/372).
>J: Theophilus Jones, _A History of the County of Brecknock_ Vol. II (Brecknock, 1809; 2nd edn., 1898), Appendix doc. IX (at  https://babel.hathitrust.org/cgi/pt?id=coo.31924096162064&view=1up&seq=724)

For the manuscripts:

>R: The National Archives, Chancery Patent Rolls, C 66/709
>C: St John's College, Cambridge, MS. H.12
>D: National Library of Wales, Chapter of St Davids manuscripts, SDCh/B/23
>O: British Library, Harley MS 1249
>H: National Library of Wales, Chapter of St Davids manuscripts, SDCh/B/24
>I: National Library of Wales, Chapter of St Davids manuscripts, SDCh/B/25
>M: National Library of Wales, Chapter of St Davids manuscripts, SDCh/B/29 (published early 20th century as _Menevia Sacra_; includes a partial copy of the Brecon charter)

**Comment by haggis78** [comment]
@ebeshero Some of the attributes/suggested values in that link should be useful, including the distinction between substantive and orthographic variant readings, and the possibility of false emendations.
